### ISSUE TITLE
About the performance using your code

### ISSUE THREAD

**Issue by Iceland-Leo** [TropComplique/multi-scale-gradient-gan#1]
Can you provide some examples of other dataset, such as flowers, face and so on. I just want to see what happens when you make a change. Is it better than the official implementation? Or the same as the official implementation? Thank you very much!

**Comment by TropComplique** [comment]
Hi.
Sorry, I don't have resources to train on other datasets right now.
I doubt that it is better than the official implementation.
I believe that my implementation needs a lot of hyperparameter tuning to work on other data.

**Comment by Iceland-Leo** [comment]
OK! Thank you so much
